blank_issues_enabled: false
contact_links:
  - name: Ask a Question / General Discussion
    url: https://github.com/<your-username>/<your-repo-name>/discussions
    about: Please ask questions and discuss ideas before filing bugs.